### ISSUE TITLE
More Players

### ISSUE THREAD

**Issue by thelilswift** [eDonnes124/Town-Of-Us-R#11]
I host tou lobbies every night, and i have to make people wait, any chance a mod can make it to 20 players?

**Comment by VirusTLNR** [comment]
not an expert by any means.. but

Crowded mod used to allow up to 127 p[layers.

Crowded mod also didnt work on public servers because you would get banned for cheating.

Therefore.. all someone needs to do is update crowded mod.. and then you need to play on a private server, and everyone needs TOU + crowded mod installed.. assuming they both work together.

but yeah.. adding it into TOU from my POV at least, would be silly.. simply because afaik, you try to jump in a public lobby with more than 10 players in the past, and it wont work out as you intended.

**Comment by whichtwix** [comment]
the crowded mod would have to be converted into 1 dll you put in the plugins folder then right? Could that be possible?

**Comment by Anusien** [comment]
You can have more than one plugin at a time as long as they don’t try to fight with each other.

**Comment by VirusTLNR** [comment]
exactly as anusien said.

there was 2 mods i put together.

anonymous impostors 1.3 by Wunax and Crowded Mod for 127 players.

both combined allowed up to 124 impostors with 127 players.. all impostors were solo.. but you can only play on private servers as crowded mod would get you banned from public, they worked as is, i made no edits.. but when i combined the mods, they conflicted at the end game, leading to the end results screen not being displayed... which was fine, as you just "guessed" who won based off what everyone saw.

i assume the conflict there was caused by anonymous impostors calculating a new win clause for solo impostors and crowded mod expecting something different.

either way, i beleive crowded mod was last updated in 10-05-2021 or maybe even 10-05-2020.. not sure... so that coding would need updating anyway for this to be a thing.

a better solution to having 20 people? split into 2 lobbies of 10.

**Comment by amsyarasyiq** [comment]
CrowdedMod is outdated, and won't likely be updated anytime soon
