### ISSUE TITLE
[Suggestion] Please add poisoner role back as its own role

### ISSUE THREAD

**Issue by p1eguy32** [eDonnes124/Town-Of-Us-R#111]
The poisoner role is a favorite among the group I play this with, it is a great way to frame someone and really make you think about what is really going on. The bomber role is a fun role too, however I do not think it should replace the poisoner role, but should be independent from it.

**Comment by predominant** [comment]
Agreed.

**Comment by eDonnes124** [comment]
I actually liked Poisoner, I won't lie, the problem with Poisoner lied with the difficulty most people found in working out the Poisoner, I'll quote a friend here, 'it is a fun and interactive role' *sarcastically*. Depending on settings you could poison someone and be on the opposite side of the map when the person died. Bomber works very similarly to Poisoner with the delay kill, however it isn't as hard to solve the Bomber as 1, most of the time you'll know immediately it was a Bomber due to multiple deaths making Swooper not a factor, and 2, you know the Bomber had to be there X seconds prior, as with Poisoner you had to solve, if it was a poison, where they got poisoned, who would've been near there at the time as well as a lot of other factors which made it really hard to solve the Poisoner. Swooper and Poisoner also didn't synergise well in the mod and that was the problem with someone just randomly exploding. Bomber and Swooper are separated enough where you can (usually) tell the difference and having a third role (Poisoner), with having people just randomly explode felt very unnecessary. Also the reason I'm deciding to remove roles now is the mod is getting very cluttered. Lots of roles is good, but it's getting to the point where there are almost too many roles which can get very confusing for new players to have to learn the mechanics of each role. That's also why I'm trying to rework bad roles such as Shifter (turned Amnesiac in v2.5.0), Seer (v2.6.0), Arsonist (v3.2.0) and now Poisoner (turned Bomber in v4.0.0). Also multiple roles serving a similar purpose isn't necessary in the mod, trying to keep them all unique is important as it gives each role their own identity.

**Comment by p1eguy32** [comment]
Personally I think the situations that are most confusing end up being the most memorable and enjoyable. I can definitely see where you're coming from, It can be confusing for new players if all the roles are enabled. Regardless though I still do feel like having the option to enable it would still be nice, for those who think it's too confusing turning the role off has always been an option. either way, I do hope you would consider adding it as it's own role at some point down the line. It was my favorite role to try to figure out and to play as
