### ISSUE TITLE
bring back features from original repository

### ISSUE THREAD

**Issue by sugoma2137** [eDonnes124/Town-Of-Us-R#121]
well,` i think this mod lacks timelord and shifter from the original mod, and i also want some new options for a lobby:

assasin and underdog: is role(meaning it will be assigned only to impostors without aley other role)[0-1 format]
assasin: chance of appearing(just like any other role)
also, i would like to get a promise for the team, that no roles will be removed further on

**Comment by AlchlcDvl** [comment]
the existence of roles within the mod depends on their impact in the game, the roles were removed for specific reasons
- shifter was replaced with amnesiac to be more balanced
- time lord was way too buggy
- camouflager was overshadowed by the camo comms feature (this one i agree should have stayed in the mod with a few alterations)
- assassin, lover and underdog were changed because they were weak on their own

**Comment by eDonnes124** [comment]
I couldn't have put it better myself. Although the other reason Time Lord was removed is that it was definitely the worst role in the mod, no questions asked, I don't really know any lobbies that had Time Lord on to be honest, it just felt it was taking up a role slot.

**Comment by sugoma2137** [comment]
i had seen many polish lobbies using it

**Comment by sugoma2137** [comment]
private, however

**Comment by sugoma2137** [comment]
and i f*****g loved shifer immortality
underdog was able to solo 14 players btw

**Comment by sugoma2137** [comment]
lovers were really weak, i know, but i think it should be an option (i play on hard settings, basically nerfing everything, so this would fit[ i am not only person like that])
If you know polish, you'd check those videos:
https://youtu.be/wT3lwMTUUSA
https://youtu.be/tHJGPP4_DOA
https://youtu.be/wMFMfcZNCuo
https://youtu.be/X57Yd_Mq6ps
https://youtu.be/YW1uU4qYC5g
https://youtu.be/HFsK1O4ZpJY
https://youtu.be/vbUbrJh9AGU
https://youtu.be/iFznWJ00Yj8?t=3
https://youtu.be/KTiQ16gbxk4
none of theese care mine, however they made the biggest among us commynity hub in poland.
they allowed me to use their videos like that

**Comment by AlchlcDvl** [comment]
well it's not that hard for someone with a bit of coding knowledge to restore the mod to its older versions/bring back old features so if you want to go ahead and try to add them back yourself

in the end, just because a small group of people still want time lord doesn't mean they speak for every player of the mod
