### ISSUE TITLE
pestilence communicate

### ISSUE THREAD

**Issue by sugoma2137** [eDonnes124/Town-Of-Us-R#131]
make a communicate about pb turning into pest like in town of salem

**Comment by sugoma2137** [comment]
well it would scare all of crewmates and make it easier for impostors

**Comment by sugoma2137** [comment]
also impostor promotion would be a good feature (this would need to add an option to all impostor roles not beidg related to killing in any way(that means not to bomber, traitor, swooper and esc)

**Comment by whichtwix** [comment]
what is impostor promotion

**Comment by FERTAILS** [comment]
> what is impostor promotion

think of it like old mafia
when godfather dies, the mafioso, who cant kill, becomes godfather and can kill

**Comment by eDonnes124** [comment]
It is easy to implement about I don't think it's needed, Plaguebearer/Pestilence is probably the weakest neutral killer and giving an alert to all players saying Pestilence is now active would make players stop interacting with others and hence make it even worse as their ability as Pestilence is that they can't die and will kill anyone who tries killing/interacting with them. In other words, adding the notification would basically make them an Impostor who can't sabotage and can't vent (depending on settings) and they have to get everyone infected in order to get there in the first place. So no, I don't think this is necessary.
