### ISSUE TITLE
[Feature Request] Add Camouflager and Time Lord back to the mod

### ISSUE THREAD

**Issue by LimeShep** [eDonnes124/Town-Of-Us-R#339]
Basically, bring back old good roles like:

Camouflager,
Time Lord
Mayor (Add an option to the politician role to automatically be the mayor)
Shifter

**Comment by eDonnes124** [comment]
"Good", definitely not. Shifter was reworked into Amnesiac, Mayor got changed because otherwise it would've been too similar to Prosecutor and also was a buggy mess, Time Lord was the most self-explanatory thing ever for why that was removed and Camouflager and camo comms serve the same purpose. None of these will return.
