### ISSUE TITLE
[Suggestion] Imposter Modifier: Eraser

### ISSUE THREAD

**Issue by TimeLord128** [eDonnes124/Town-Of-Us-R#62]
Alongside the Assassin the other imposter can be a Modifier Erasure. This can help discourage people from calling out their modifiers such as bait.
It can also introduce interesting dynamics. An example is a Lover Couple is suddenly unable to chat after a round or two, or someone with Torch no longer being able to see after a few rounds.
Perhaps make flash and giant be able to be toggled options since those are obvious modifiers, but still keeping it an option can still make interesting dynamics. Why was the Giant modifier erased? Was the imposter trying to be nice? Or was the other Imposter a giant so they erased it to help themselves. 
If an imposter believes the flash is a sheriff, glitch, or arsonist they could take that away to the imposters benefit.
I do believe you shouldn’t be able to erase your own modifier though. Luck of the draw and you work with the cards you are dealt with.

**Comment by MyDragonBreath** [comment]
I've tried my hand at implementing this, b/c seems like a cool dynamic. (And I've been falsely voted out because someones claimed bait before 😞)

Now its quite rough so expect a few bugs, but if you want to try it out I've put a release here: [Erase-Ability-v3.0.1](https://github.com/MyDragonBreath/MDB-TownOfUs-Branch-Releases/releases/tag/v3.0.1-erase-ability)
You can check the source changes here: [master <- MyDragonBreath:erase-ability](https://github.com/eDonnes124/Town-Of-Us-R/compare/master...MyDragonBreath:erase-ability)
And view the actual source here: [MyDragonBreath:erase-ability](https://github.com/MyDragonBreath/Town-Of-Us-R/tree/erase-ability)

I'm not sure how well I've replicated this concept - but I gave it a good shot, so let me know what you think.

All the people in your lobby are going to need the same release or you'll encounter some weird rpc issues.

I do realise how horrifically I've placed the button to switch between assassin and erase when the separate ability setting is toggled off

**Comment by ponyzerteal** [comment]
> I've tried my hand at implementing this, b/c seems like a cool dynamic. (And I've been falsely voted out because someones claimed bait before 😞)
> 
> Now its quite rough so expect a few bugs, but if you want to try it out I've put a release here: [Erase-Ability-v3.0.1](https://github.com/MyDragonBreath/MDB-TownOfUs-Branch-Releases/releases/tag/v3.0.1-erase-ability) You can check the source changes here: [master <- MyDragonBreath:erase-ability](https://github.com/eDonnes124/Town-Of-Us-R/compare/master...MyDragonBreath:erase-ability) And view the actual source here: [MyDragonBreath:erase-ability](https://github.com/MyDragonBreath/Town-Of-Us-R/tree/erase-ability)
> 
> I'm not sure how well I've replicated this concept - but I gave it a good shot, so let me know what you think.
> 
> All the people in your lobby are going to need the same release or you'll encounter some weird rpc issues.
> 
> I do realise how horrifically I've placed the button to switch between assassin and erase when the separate ability setting is toggled off
> 
> (also i can't do button art)

very well，Thank you for your work！
