### ISSUE TITLE
[Suggestion] Makes tasks more relevant

### ISSUE THREAD

**Issue by AldiandyaIrsyad** [eDonnes124/Town-Of-Us-R#80]
Currently, a lot of lobbies seems doesn't just do tasks and just roam around and find the killers. I think an option that allows you to have tasks more beneficial would be better.

An example of this may be an option such as getting extra caution for Veterans, clear a person out for sheriff, increase feet duration for investigator, etc.

**Comment by VergilSkye** [comment]
i'm on the same page.  I was looking on the mods to see if has anything like this.

it's very frustrating to be
crewmate and have allies who don't do tasks, and you lose because you have a 0/8 person on team.

An option to at least remove ghost tasks or, at least, force astronauts to do 1 task per meeting would be great.


Does anyone have any suggestions for this problem?

**Comment by Dxgamer7405** [comment]
> i'm on the same page. I was looking on the mods to see if has anything like this.
> 
> it's very frustrating to be crewmate and have allies who don't do tasks, and you lose because you have a 0/8 person on team.
> 
> An option to at least remove ghost tasks or, at least, force astronauts to do 1 task per meeting would be great.
> 
> Does anyone have any suggestions for this problem?

A configuration so that ghost people's tasks are done alone (in a slow way so it doesn't get boring and difficult for imposters)

**Comment by whichtwix** [comment]
wdym by done alone?
